name: islamic_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  introduction_screen: ^3.1.14
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  carousel_slider: ^5.0.0
  animated_button_bar: ^0.0.2
  hijri: ^3.0.0
  intl: ^0.18.0
  adhan: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter_native_splash:

  color: "#FFFFFF"
  background_image: "assets/images/Splash Screen.png"

  #  image: assets/images/Splash Screen.png


  android_12:
    image: assets/images/Splash Screen.png

    color: "#202020"
    branding: assets/images/ic_splash.png

    image_android: assets/images/Splash Screen.png
    image_dark_android: assets/images/Splash Screen.png
    background_image_android: "assets/images/Splash Screen.png"
    background_image_dark_android: "assets/images/Splash Screen.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
